### ISSUE TITLE
parallelize sourcemaps upload

### ISSUE THREAD

**Issue by mbrevda** [LogRocket/logrocket-cli#6]
Currently, sourcemaps are uploaded consecutively. In larger projects uploading the files in parallel could help shave some time off the build process. While it doesn't seem like a lot, when deploying to semi-production (like per-branch builds), these times add up quickly!

**Comment by eranimo** [comment]
@mbrevda Good idea, we should do that. I'll add that to our list of things for the next release. How long does it take you to upload all your sourcemaps currently?

**Comment by mbrevda** [comment]
About 15 seconds, with a relatively small amount of files, about 2-3 seconds per `.map`. We expect this to grow exponenetionally as we start code-splitting more.

While this isn't a whole lot of time when running multiple builds per day this all adds up.

Thanks!

**Comment by eranimo** [comment]
Done in https://github.com/LogRocket/logrocket-cli/pull/7 !

**Comment by mbrevda** [comment]
Thanks so much! Whem can we get a version bump published to npm?

**Comment by ammardodin** [comment]
Hey @mbrevda the `0.11.0`. Please give it a shot and let me know if it improves things for you.

**Comment by mbrevda** [comment]
Amazing - cut down upload time by 92%! 🚀
